//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimeTracker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Add... ähnelt.
        /// </summary>
        public static string BUTTON_ADD {
            get {
                return ResourceManager.GetString("BUTTON_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Cancel ähnelt.
        /// </summary>
        public static string BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Edit... ähnelt.
        /// </summary>
        public static string BUTTON_EDIT {
            get {
                return ResourceManager.GetString("BUTTON_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Free working days... ähnelt.
        /// </summary>
        public static string BUTTON_FREEDAYS {
            get {
                return ResourceManager.GetString("BUTTON_FREEDAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _OK ähnelt.
        /// </summary>
        public static string BUTTON_OK {
            get {
                return ResourceManager.GetString("BUTTON_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Refresh ähnelt.
        /// </summary>
        public static string BUTTON_REFRESH {
            get {
                return ResourceManager.GetString("BUTTON_REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Remove ähnelt.
        /// </summary>
        public static string BUTTON_REMOVE {
            get {
                return ResourceManager.GetString("BUTTON_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _About ähnelt.
        /// </summary>
        public static string CMD_ABOUT {
            get {
                return ResourceManager.GetString("CMD_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Add ähnelt.
        /// </summary>
        public static string CMD_ADD {
            get {
                return ResourceManager.GetString("CMD_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculate _Overtime... ähnelt.
        /// </summary>
        public static string CMD_CALCULATE_OVERTIME {
            get {
                return ResourceManager.GetString("CMD_CALCULATE_OVERTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Close ähnelt.
        /// </summary>
        public static string CMD_CLOSE {
            get {
                return ResourceManager.GetString("CMD_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configure _Projects... ähnelt.
        /// </summary>
        public static string CMD_CONFIGURE_PROJECTS {
            get {
                return ResourceManager.GetString("CMD_CONFIGURE_PROJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Delete ähnelt.
        /// </summary>
        public static string CMD_DELETE {
            get {
                return ResourceManager.GetString("CMD_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Edit ähnelt.
        /// </summary>
        public static string CMD_EDIT {
            get {
                return ResourceManager.GetString("CMD_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Exit ähnelt.
        /// </summary>
        public static string CMD_EXIT {
            get {
                return ResourceManager.GetString("CMD_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Merge ähnelt.
        /// </summary>
        public static string CMD_MERGE {
            get {
                return ResourceManager.GetString("CMD_MERGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Next ähnelt.
        /// </summary>
        public static string CMD_NEXT {
            get {
                return ResourceManager.GetString("CMD_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Previous ähnelt.
        /// </summary>
        public static string CMD_PREVIOUS {
            get {
                return ResourceManager.GetString("CMD_PREVIOUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Start ähnelt.
        /// </summary>
        public static string CMD_START {
            get {
                return ResourceManager.GetString("CMD_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die S_top ähnelt.
        /// </summary>
        public static string CMD_STOP {
            get {
                return ResourceManager.GetString("CMD_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Days ähnelt.
        /// </summary>
        public static string COLUMN_DAYS {
            get {
                return ResourceManager.GetString("COLUMN_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        public static string COLUMN_DESCRIPTION {
            get {
                return ResourceManager.GetString("COLUMN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Duration ähnelt.
        /// </summary>
        public static string COLUMN_DURATION {
            get {
                return ResourceManager.GetString("COLUMN_DURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End ähnelt.
        /// </summary>
        public static string COLUMN_ENDTIME {
            get {
                return ResourceManager.GetString("COLUMN_ENDTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die From ähnelt.
        /// </summary>
        public static string COLUMN_FROM {
            get {
                return ResourceManager.GetString("COLUMN_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string COLUMN_NAME {
            get {
                return ResourceManager.GetString("COLUMN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overtime ähnelt.
        /// </summary>
        public static string COLUMN_OVERTIME {
            get {
                return ResourceManager.GetString("COLUMN_OVERTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project ähnelt.
        /// </summary>
        public static string COLUMN_PROJECT {
            get {
                return ResourceManager.GetString("COLUMN_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Required working time ähnelt.
        /// </summary>
        public static string COLUMN_REQUIREDWORKTIME {
            get {
                return ResourceManager.GetString("COLUMN_REQUIREDWORKTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        /// </summary>
        public static string COLUMN_STARTTIME {
            get {
                return ResourceManager.GetString("COLUMN_STARTTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Period ähnelt.
        /// </summary>
        public static string COLUMN_TIMESPAN {
            get {
                return ResourceManager.GetString("COLUMN_TIMESPAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To ähnelt.
        /// </summary>
        public static string COLUMN_TO {
            get {
                return ResourceManager.GetString("COLUMN_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Week ähnelt.
        /// </summary>
        public static string COLUMN_WEEK {
            get {
                return ResourceManager.GetString("COLUMN_WEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Working time ähnelt.
        /// </summary>
        public static string COLUMN_WORKTIME {
            get {
                return ResourceManager.GetString("COLUMN_WORKTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Year ähnelt.
        /// </summary>
        public static string COLUMN_YEAR {
            get {
                return ResourceManager.GetString("COLUMN_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occurred. {0} ähnelt.
        /// </summary>
        public static string ERROR_OCCURRED_0 {
            get {
                return ResourceManager.GetString("ERROR_OCCURRED_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Date: ähnelt.
        /// </summary>
        public static string LABEL_DATE {
            get {
                return ResourceManager.GetString("LABEL_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Desc_ription: ähnelt.
        /// </summary>
        public static string LABEL_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _End Time Hour: ähnelt.
        /// </summary>
        public static string LABEL_ENDTIME_HOUR {
            get {
                return ResourceManager.GetString("LABEL_ENDTIME_HOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End Time M_inute: ähnelt.
        /// </summary>
        public static string LABEL_ENDTIME_MINUTE {
            get {
                return ResourceManager.GetString("LABEL_ENDTIME_MINUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _From: ähnelt.
        /// </summary>
        public static string LABEL_FROM {
            get {
                return ResourceManager.GetString("LABEL_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Hours/Day ähnelt.
        /// </summary>
        public static string LABEL_HOURSPERDAY {
            get {
                return ResourceManager.GetString("LABEL_HOURSPERDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Working hours per week: ähnelt.
        /// </summary>
        public static string LABEL_HOURSPERWEEK {
            get {
                return ResourceManager.GetString("LABEL_HOURSPERWEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Name: ähnelt.
        /// </summary>
        public static string LABEL_NAME {
            get {
                return ResourceManager.GetString("LABEL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Overtime balance: ähnelt.
        /// </summary>
        public static string LABEL_PREVPLUSHOURS {
            get {
                return ResourceManager.GetString("LABEL_PREVPLUSHOURS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Project: ähnelt.
        /// </summary>
        public static string LABEL_PROJECT {
            get {
                return ResourceManager.GetString("LABEL_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Start calculation day: ähnelt.
        /// </summary>
        public static string LABEL_STARTDAYCALC {
            get {
                return ResourceManager.GetString("LABEL_STARTDAYCALC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Start Time Hour: ähnelt.
        /// </summary>
        public static string LABEL_STARTTIME_HOUR {
            get {
                return ResourceManager.GetString("LABEL_STARTTIME_HOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Time _Minute: ähnelt.
        /// </summary>
        public static string LABEL_STARTTIME_MINUTE {
            get {
                return ResourceManager.GetString("LABEL_STARTTIME_MINUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _To: ähnelt.
        /// </summary>
        public static string LABEL_TO {
            get {
                return ResourceManager.GetString("LABEL_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Working days per week: ähnelt.
        /// </summary>
        public static string LABEL_WORKDAYSPERWEEK {
            get {
                return ResourceManager.GetString("LABEL_WORKDAYSPERWEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Edit ähnelt.
        /// </summary>
        public static string MENUITEM_EDIT {
            get {
                return ResourceManager.GetString("MENUITEM_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _File ähnelt.
        /// </summary>
        public static string MENUITEM_FILE {
            get {
                return ResourceManager.GetString("MENUITEM_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Help ähnelt.
        /// </summary>
        public static string MENUITEM_HELP {
            get {
                return ResourceManager.GetString("MENUITEM_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to delete the selected working times? ähnelt.
        /// </summary>
        public static string QUESTION_DELETE_ITEMS {
            get {
                return ResourceManager.GetString("QUESTION_DELETE_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copyright 2018 Niels Stockfleth
        ///
        ///This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
        ///
        ///This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details. ähnelt.
        /// </summary>
        public static string TEXT_COPYRIGHT {
            get {
                return ResourceManager.GetString("TEXT_COPYRIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default project ähnelt.
        /// </summary>
        public static string TEXT_DEFAULT_PROJECT {
            get {
                return ResourceManager.GetString("TEXT_DEFAULT_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monday to Friday ähnelt.
        /// </summary>
        public static string TEXT_MONDAYTOFRIDAY {
            get {
                return ResourceManager.GetString("TEXT_MONDAYTOFRIDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overtime from {0} to {1} ähnelt.
        /// </summary>
        public static string TEXT_OVERTIME_0_1 {
            get {
                return ResourceManager.GetString("TEXT_OVERTIME_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Working time recording started on {0} at {1} for {2} hours. ähnelt.
        /// </summary>
        public static string TEXT_RECORD_START_0_1_2 {
            get {
                return ResourceManager.GetString("TEXT_RECORD_START_0_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Working time recording stopped. ähnelt.
        /// </summary>
        public static string TEXT_RECORD_STOP {
            get {
                return ResourceManager.GetString("TEXT_RECORD_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total working time on {0}: {1} hours. ähnelt.
        /// </summary>
        public static string TEXT_TOTAL_0_1 {
            get {
                return ResourceManager.GetString("TEXT_TOTAL_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total overtime: {0} ähnelt.
        /// </summary>
        public static string TEXT_TOTAL_OVERTIME_0 {
            get {
                return ResourceManager.GetString("TEXT_TOTAL_OVERTIME_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Working Time ähnelt.
        /// </summary>
        public static string TITLE_ADD {
            get {
                return ResourceManager.GetString("TITLE_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configure Free Working Days ähnelt.
        /// </summary>
        public static string TITLE_CONFIGURE_FREEDAYS {
            get {
                return ResourceManager.GetString("TITLE_CONFIGURE_FREEDAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configure Projects ähnelt.
        /// </summary>
        public static string TITLE_CONFIGURE_PROJECT {
            get {
                return ResourceManager.GetString("TITLE_CONFIGURE_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Working Time ähnelt.
        /// </summary>
        public static string TITLE_EDIT {
            get {
                return ResourceManager.GetString("TITLE_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Free Working Days ähnelt.
        /// </summary>
        public static string TITLE_EDIT_FREEDAYS {
            get {
                return ResourceManager.GetString("TITLE_EDIT_FREEDAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Project ähnelt.
        /// </summary>
        public static string TITLE_EDIT_PROJECT {
            get {
                return ResourceManager.GetString("TITLE_EDIT_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculate Overtime ähnelt.
        /// </summary>
        public static string TITLE_OVERTIME {
            get {
                return ResourceManager.GetString("TITLE_OVERTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Working Time Recording ähnelt.
        /// </summary>
        public static string TITLE_TIMETRACKER {
            get {
                return ResourceManager.GetString("TITLE_TIMETRACKER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add working time ähnelt.
        /// </summary>
        public static string TOOLTIP_ADD {
            get {
                return ResourceManager.GetString("TOOLTIP_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit working time ähnelt.
        /// </summary>
        public static string TOOLTIP_EDIT {
            get {
                return ResourceManager.GetString("TOOLTIP_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select next day ähnelt.
        /// </summary>
        public static string TOOLTIP_NEXT {
            get {
                return ResourceManager.GetString("TOOLTIP_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select previous day ähnelt.
        /// </summary>
        public static string TOOLTIP_PREVIOUS {
            get {
                return ResourceManager.GetString("TOOLTIP_PREVIOUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove working time ähnelt.
        /// </summary>
        public static string TOOLTIP_REMOVE {
            get {
                return ResourceManager.GetString("TOOLTIP_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start working time recording ähnelt.
        /// </summary>
        public static string TOOLTIP_START {
            get {
                return ResourceManager.GetString("TOOLTIP_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop working time recording ähnelt.
        /// </summary>
        public static string TOOLTIP_STOP {
            get {
                return ResourceManager.GetString("TOOLTIP_STOP", resourceCulture);
            }
        }
    }
}
